### ISSUE TITLE
Flow example request

### ISSUE THREAD

**Issue by Vrijheid13** [joabakk/signalk-pebble-mydata#1]
Hi,
Your app seems great, but i don't seem to get it to work. Is it possible to share an example of the Flow from the NodeRed interface? So i can copy clip this in my working SignalK server?

regards,
Wouter

**Comment by joabakk** [comment]
Hm, I am not familiar with node-red. This was designed as a plugin to the signalk-server-node package, which has a method to show plugins such as this one. I think you would need to cater for plugins from your node-red installation. 

I have been using Openplotter too, but the basic signalk-server-node is developing faster, and you would find most of the same functions is or will be possible from there. Plugins such as this being one of the additional features.

**Comment by joabakk** [comment]
I've changed the description in readme to reflect this. Closing this issue
