### ISSUE TITLE
Install issue within the OpenPlotter OS

### ISSUE THREAD

**Issue by Vrijheid13** [joabakk/signalk-pebble-mydata#15]
On a previous version of the OpenplotterOS, i've used the Signalk-Pebble-Mydata rather often. And it works great. With the updated OS of Openplotter, I don't seem to get the npm installed.

Could you have a look at the openmarine forum, where I've opened a post on this..
http://forum.openmarine.net/showthread.php?tid=1280

regards,
Wouter

**Comment by joabakk** [comment]
That sounds strange. Having said that, the app store is behaving strange just now as there is a problem with npm search (https://status.npmjs.org/incidents/frcp18csxlks). It may be related, or it may be openplotter. I will try to reinstall on my server, although it is not OP

**Comment by Vrijheid13** [comment]
Did you get it to work on your own server?
I've re-installed my system. And after that, installed the "Signalk-pebble-mydata" plugin. And it returns an error "Failed to start. Cannot find module 'explorer'"

Do you know what this means?

**Comment by joabakk** [comment]
Hi again,
No, I have not had time to test with OP. The code does not include any "explorer", so that must be openplotter specific. I just installed on my native SK server, and it works as expected. I haven't played with Openplotter in years

**Comment by joabakk** [comment]
@Vrijheid13 have you tried the latest version of the plugin?
